version: '3.9'
services:
  db:
    container_name: coffee-db
    image: postgres:15-alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=coffee
      - POSTGRES_PASSWORD=coffee
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    container_name: coffee-redis
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'

volumes:
  db:
    driver: local